openapi: 3.0.4
info:
  title: Roman Numeral Converter
  description: Roman Numeral Converter is a bidirectional tool for converting between Arabic numbers (1-3999) and Roman numerals. It provides detailed breakdowns of the conversion process.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.9
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
- url: https://api.apiverve.com/
paths:
  /v1/romanconverter:
    get:
      summary: Convert Roman Numerals
      description: Roman Numeral Converter is a bidirectional tool for converting between Arabic numbers (1-3999) and Roman numerals. It provides detailed breakdowns of the conversion process.
      operationId: romanconverter
      parameters:
      - name: number
        in: query
        schema:
          type: integer
        required: false
        description: The number to convert to Roman numerals (1-3999)
        example: '2024'
      - name: roman
        in: query
        schema:
          type: string
        required: false
        description: The Roman numeral to convert to a number
        example: MMXXIV
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: string
                    description: data
              example:
                status: ok
                error: 
                data:
                  number: 2024
                  roman: MMXXIV
                  breakdown:
                    M: 2
                    X: 2
                    IV: 1
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occured, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
- api_key: []
